import React, { useState } from 'react';
import {
    View,
    StyleSheet,
    Button,
    Alert,
    ActivityIndicator
} from 'react-native';
import { useSession } from './_layout';

export default function SettingsScreen() {
    const { signOut } = useSession();
    const [busy, setBusy] = useState(false);

    const handleSignOut = async () => {
        setBusy(true);
        try {
            await signOut();
            // Sign-out is handled by the root layout, which will redirect to the login screen.
        } catch (e: any) {
            Alert.alert('Sign Out Error', e.message);
        } finally {
            setBusy(false);
        }
    };

    return (
        <View style={styles.container}>
            {/* The header is now automatically-generated by the Stack navigator */}
            <View style={styles.content}>
                <View style={styles.signOutButtonContainer}>
                    {busy ? (
                        <ActivityIndicator />
                    ) : (
                        <Button title="Sign out" color="#c1121f" onPress={handleSignOut} />
                    )}
                </View>
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white',
    },
    content: {
        flex: 1,
        justifyContent: 'flex-end', // Aligns children to the bottom
        alignItems: 'center',
        paddingBottom: 40, // Add some padding at the bottom
    },
    signOutButtonContainer: {
        width: '80%',
    },
});
